// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PictureSpider.proto

package com.piggy.quincy.utils.picture;

public final class PictureSpiderService {
  private PictureSpiderService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PictureUrlRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.v1.PictureUrlRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    String getType();
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    String getId();
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int64 manga = 3;</code>
     * @return The manga.
     */
    long getManga();

    /**
     * <code>bool cache = 4;</code>
     * @return The cache.
     */
    boolean getCache();

    /**
     * <code>bool uploadSM = 5;</code>
     * @return The uploadSM.
     */
    boolean getUploadSM();
  }
  /**
   * Protobuf type {@code proto.v1.PictureUrlRequest}
   */
  public  static final class PictureUrlRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.v1.PictureUrlRequest)
      PictureUrlRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PictureUrlRequest.newBuilder() to construct.
    private PictureUrlRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PictureUrlRequest() {
      type_ = "";
      id_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PictureUrlRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PictureUrlRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 24: {

              manga_ = input.readInt64();
              break;
            }
            case 32: {

              cache_ = input.readBool();
              break;
            }
            case 40: {

              uploadSM_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PictureSpiderService.internal_static_proto_v1_PictureUrlRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PictureSpiderService.internal_static_proto_v1_PictureUrlRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PictureUrlRequest.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile Object type_;
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private volatile Object id_;
    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MANGA_FIELD_NUMBER = 3;
    private long manga_;
    /**
     * <code>int64 manga = 3;</code>
     * @return The manga.
     */
    public long getManga() {
      return manga_;
    }

    public static final int CACHE_FIELD_NUMBER = 4;
    private boolean cache_;
    /**
     * <code>bool cache = 4;</code>
     * @return The cache.
     */
    public boolean getCache() {
      return cache_;
    }

    public static final int UPLOADSM_FIELD_NUMBER = 5;
    private boolean uploadSM_;
    /**
     * <code>bool uploadSM = 5;</code>
     * @return The uploadSM.
     */
    public boolean getUploadSM() {
      return uploadSM_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
      }
      if (manga_ != 0L) {
        output.writeInt64(3, manga_);
      }
      if (cache_ != false) {
        output.writeBool(4, cache_);
      }
      if (uploadSM_ != false) {
        output.writeBool(5, uploadSM_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
      }
      if (manga_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, manga_);
      }
      if (cache_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, cache_);
      }
      if (uploadSM_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, uploadSM_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PictureUrlRequest)) {
        return super.equals(obj);
      }
      PictureUrlRequest other = (PictureUrlRequest) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (!getId()
          .equals(other.getId())) return false;
      if (getManga()
          != other.getManga()) return false;
      if (getCache()
          != other.getCache()) return false;
      if (getUploadSM()
          != other.getUploadSM()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + MANGA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getManga());
      hash = (37 * hash) + CACHE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCache());
      hash = (37 * hash) + UPLOADSM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUploadSM());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PictureUrlRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PictureUrlRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PictureUrlRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PictureUrlRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PictureUrlRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PictureUrlRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PictureUrlRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PictureUrlRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PictureUrlRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PictureUrlRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PictureUrlRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PictureUrlRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PictureUrlRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.v1.PictureUrlRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.v1.PictureUrlRequest)
        PictureUrlRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PictureSpiderService.internal_static_proto_v1_PictureUrlRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PictureSpiderService.internal_static_proto_v1_PictureUrlRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PictureUrlRequest.class, Builder.class);
      }

      // Construct using com.piggy.quincy.utils.picture.PictureSpiderService.PictureUrlRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = "";

        id_ = "";

        manga_ = 0L;

        cache_ = false;

        uploadSM_ = false;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PictureSpiderService.internal_static_proto_v1_PictureUrlRequest_descriptor;
      }

      @Override
      public PictureUrlRequest getDefaultInstanceForType() {
        return PictureUrlRequest.getDefaultInstance();
      }

      @Override
      public PictureUrlRequest build() {
        PictureUrlRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PictureUrlRequest buildPartial() {
        PictureUrlRequest result = new PictureUrlRequest(this);
        result.type_ = type_;
        result.id_ = id_;
        result.manga_ = manga_;
        result.cache_ = cache_;
        result.uploadSM_ = uploadSM_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PictureUrlRequest) {
          return mergeFrom((PictureUrlRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PictureUrlRequest other) {
        if (other == PictureUrlRequest.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getManga() != 0L) {
          setManga(other.getManga());
        }
        if (other.getCache() != false) {
          setCache(other.getCache());
        }
        if (other.getUploadSM() != false) {
          setUploadSM(other.getUploadSM());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PictureUrlRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PictureUrlRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object type_ = "";
      /**
       * <code>string type = 1;</code>
       * @return The type.
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {

        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        type_ = value;
        onChanged();
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 2;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 2;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        id_ = value;
        onChanged();
        return this;
      }

      private long manga_ ;
      /**
       * <code>int64 manga = 3;</code>
       * @return The manga.
       */
      public long getManga() {
        return manga_;
      }
      /**
       * <code>int64 manga = 3;</code>
       * @param value The manga to set.
       * @return This builder for chaining.
       */
      public Builder setManga(long value) {

        manga_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 manga = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearManga() {

        manga_ = 0L;
        onChanged();
        return this;
      }

      private boolean cache_ ;
      /**
       * <code>bool cache = 4;</code>
       * @return The cache.
       */
      public boolean getCache() {
        return cache_;
      }
      /**
       * <code>bool cache = 4;</code>
       * @param value The cache to set.
       * @return This builder for chaining.
       */
      public Builder setCache(boolean value) {

        cache_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool cache = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCache() {

        cache_ = false;
        onChanged();
        return this;
      }

      private boolean uploadSM_ ;
      /**
       * <code>bool uploadSM = 5;</code>
       * @return The uploadSM.
       */
      public boolean getUploadSM() {
        return uploadSM_;
      }
      /**
       * <code>bool uploadSM = 5;</code>
       * @param value The uploadSM to set.
       * @return This builder for chaining.
       */
      public Builder setUploadSM(boolean value) {

        uploadSM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool uploadSM = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUploadSM() {

        uploadSM_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.v1.PictureUrlRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.v1.PictureUrlRequest)
    private static final PictureUrlRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PictureUrlRequest();
    }

    public static PictureUrlRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PictureUrlRequest>
        PARSER = new com.google.protobuf.AbstractParser<PictureUrlRequest>() {
      @Override
      public PictureUrlRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PictureUrlRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PictureUrlRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PictureUrlRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public PictureUrlRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PictureUrlDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.v1.PictureUrlData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string originalUrl = 1;</code>
     * @return The originalUrl.
     */
    String getOriginalUrl();
    /**
     * <code>string originalUrl = 1;</code>
     * @return The bytes for originalUrl.
     */
    com.google.protobuf.ByteString
        getOriginalUrlBytes();

    /**
     * <code>string referer = 2;</code>
     * @return The referer.
     */
    String getReferer();
    /**
     * <code>string referer = 2;</code>
     * @return The bytes for referer.
     */
    com.google.protobuf.ByteString
        getRefererBytes();

    /**
     * <code>string cacheUrl = 3;</code>
     * @return The cacheUrl.
     */
    String getCacheUrl();
    /**
     * <code>string cacheUrl = 3;</code>
     * @return The bytes for cacheUrl.
     */
    com.google.protobuf.ByteString
        getCacheUrlBytes();

    /**
     * <code>string smUrl = 4;</code>
     * @return The smUrl.
     */
    String getSmUrl();
    /**
     * <code>string smUrl = 4;</code>
     * @return The bytes for smUrl.
     */
    com.google.protobuf.ByteString
        getSmUrlBytes();

    /**
     * <code>bool isR18 = 5;</code>
     * @return The isR18.
     */
    boolean getIsR18();
  }
  /**
   * Protobuf type {@code proto.v1.PictureUrlData}
   */
  public  static final class PictureUrlData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.v1.PictureUrlData)
      PictureUrlDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PictureUrlData.newBuilder() to construct.
    private PictureUrlData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PictureUrlData() {
      originalUrl_ = "";
      referer_ = "";
      cacheUrl_ = "";
      smUrl_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PictureUrlData();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PictureUrlData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              originalUrl_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              referer_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              cacheUrl_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              smUrl_ = s;
              break;
            }
            case 40: {

              isR18_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PictureSpiderService.internal_static_proto_v1_PictureUrlData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PictureSpiderService.internal_static_proto_v1_PictureUrlData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PictureUrlData.class, Builder.class);
    }

    public static final int ORIGINALURL_FIELD_NUMBER = 1;
    private volatile Object originalUrl_;
    /**
     * <code>string originalUrl = 1;</code>
     * @return The originalUrl.
     */
    public String getOriginalUrl() {
      Object ref = originalUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        originalUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string originalUrl = 1;</code>
     * @return The bytes for originalUrl.
     */
    public com.google.protobuf.ByteString
        getOriginalUrlBytes() {
      Object ref = originalUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        originalUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERER_FIELD_NUMBER = 2;
    private volatile Object referer_;
    /**
     * <code>string referer = 2;</code>
     * @return The referer.
     */
    public String getReferer() {
      Object ref = referer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        referer_ = s;
        return s;
      }
    }
    /**
     * <code>string referer = 2;</code>
     * @return The bytes for referer.
     */
    public com.google.protobuf.ByteString
        getRefererBytes() {
      Object ref = referer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        referer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CACHEURL_FIELD_NUMBER = 3;
    private volatile Object cacheUrl_;
    /**
     * <code>string cacheUrl = 3;</code>
     * @return The cacheUrl.
     */
    public String getCacheUrl() {
      Object ref = cacheUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cacheUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string cacheUrl = 3;</code>
     * @return The bytes for cacheUrl.
     */
    public com.google.protobuf.ByteString
        getCacheUrlBytes() {
      Object ref = cacheUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cacheUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SMURL_FIELD_NUMBER = 4;
    private volatile Object smUrl_;
    /**
     * <code>string smUrl = 4;</code>
     * @return The smUrl.
     */
    public String getSmUrl() {
      Object ref = smUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        smUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string smUrl = 4;</code>
     * @return The bytes for smUrl.
     */
    public com.google.protobuf.ByteString
        getSmUrlBytes() {
      Object ref = smUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        smUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISR18_FIELD_NUMBER = 5;
    private boolean isR18_;
    /**
     * <code>bool isR18 = 5;</code>
     * @return The isR18.
     */
    public boolean getIsR18() {
      return isR18_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOriginalUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, originalUrl_);
      }
      if (!getRefererBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, referer_);
      }
      if (!getCacheUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cacheUrl_);
      }
      if (!getSmUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, smUrl_);
      }
      if (isR18_ != false) {
        output.writeBool(5, isR18_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOriginalUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, originalUrl_);
      }
      if (!getRefererBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, referer_);
      }
      if (!getCacheUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cacheUrl_);
      }
      if (!getSmUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, smUrl_);
      }
      if (isR18_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isR18_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PictureUrlData)) {
        return super.equals(obj);
      }
      PictureUrlData other = (PictureUrlData) obj;

      if (!getOriginalUrl()
          .equals(other.getOriginalUrl())) return false;
      if (!getReferer()
          .equals(other.getReferer())) return false;
      if (!getCacheUrl()
          .equals(other.getCacheUrl())) return false;
      if (!getSmUrl()
          .equals(other.getSmUrl())) return false;
      if (getIsR18()
          != other.getIsR18()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ORIGINALURL_FIELD_NUMBER;
      hash = (53 * hash) + getOriginalUrl().hashCode();
      hash = (37 * hash) + REFERER_FIELD_NUMBER;
      hash = (53 * hash) + getReferer().hashCode();
      hash = (37 * hash) + CACHEURL_FIELD_NUMBER;
      hash = (53 * hash) + getCacheUrl().hashCode();
      hash = (37 * hash) + SMURL_FIELD_NUMBER;
      hash = (53 * hash) + getSmUrl().hashCode();
      hash = (37 * hash) + ISR18_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsR18());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PictureUrlData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PictureUrlData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PictureUrlData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PictureUrlData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PictureUrlData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PictureUrlData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PictureUrlData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PictureUrlData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PictureUrlData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PictureUrlData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PictureUrlData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PictureUrlData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PictureUrlData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.v1.PictureUrlData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.v1.PictureUrlData)
        PictureUrlDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PictureSpiderService.internal_static_proto_v1_PictureUrlData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PictureSpiderService.internal_static_proto_v1_PictureUrlData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PictureUrlData.class, Builder.class);
      }

      // Construct using com.piggy.quincy.utils.picture.PictureSpiderService.PictureUrlData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        originalUrl_ = "";

        referer_ = "";

        cacheUrl_ = "";

        smUrl_ = "";

        isR18_ = false;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PictureSpiderService.internal_static_proto_v1_PictureUrlData_descriptor;
      }

      @Override
      public PictureUrlData getDefaultInstanceForType() {
        return PictureUrlData.getDefaultInstance();
      }

      @Override
      public PictureUrlData build() {
        PictureUrlData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PictureUrlData buildPartial() {
        PictureUrlData result = new PictureUrlData(this);
        result.originalUrl_ = originalUrl_;
        result.referer_ = referer_;
        result.cacheUrl_ = cacheUrl_;
        result.smUrl_ = smUrl_;
        result.isR18_ = isR18_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PictureUrlData) {
          return mergeFrom((PictureUrlData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PictureUrlData other) {
        if (other == PictureUrlData.getDefaultInstance()) return this;
        if (!other.getOriginalUrl().isEmpty()) {
          originalUrl_ = other.originalUrl_;
          onChanged();
        }
        if (!other.getReferer().isEmpty()) {
          referer_ = other.referer_;
          onChanged();
        }
        if (!other.getCacheUrl().isEmpty()) {
          cacheUrl_ = other.cacheUrl_;
          onChanged();
        }
        if (!other.getSmUrl().isEmpty()) {
          smUrl_ = other.smUrl_;
          onChanged();
        }
        if (other.getIsR18() != false) {
          setIsR18(other.getIsR18());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PictureUrlData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PictureUrlData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object originalUrl_ = "";
      /**
       * <code>string originalUrl = 1;</code>
       * @return The originalUrl.
       */
      public String getOriginalUrl() {
        Object ref = originalUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          originalUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string originalUrl = 1;</code>
       * @return The bytes for originalUrl.
       */
      public com.google.protobuf.ByteString
          getOriginalUrlBytes() {
        Object ref = originalUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          originalUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string originalUrl = 1;</code>
       * @param value The originalUrl to set.
       * @return This builder for chaining.
       */
      public Builder setOriginalUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        originalUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string originalUrl = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOriginalUrl() {

        originalUrl_ = getDefaultInstance().getOriginalUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string originalUrl = 1;</code>
       * @param value The bytes for originalUrl to set.
       * @return This builder for chaining.
       */
      public Builder setOriginalUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        originalUrl_ = value;
        onChanged();
        return this;
      }

      private Object referer_ = "";
      /**
       * <code>string referer = 2;</code>
       * @return The referer.
       */
      public String getReferer() {
        Object ref = referer_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          referer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string referer = 2;</code>
       * @return The bytes for referer.
       */
      public com.google.protobuf.ByteString
          getRefererBytes() {
        Object ref = referer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          referer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string referer = 2;</code>
       * @param value The referer to set.
       * @return This builder for chaining.
       */
      public Builder setReferer(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        referer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string referer = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReferer() {

        referer_ = getDefaultInstance().getReferer();
        onChanged();
        return this;
      }
      /**
       * <code>string referer = 2;</code>
       * @param value The bytes for referer to set.
       * @return This builder for chaining.
       */
      public Builder setRefererBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        referer_ = value;
        onChanged();
        return this;
      }

      private Object cacheUrl_ = "";
      /**
       * <code>string cacheUrl = 3;</code>
       * @return The cacheUrl.
       */
      public String getCacheUrl() {
        Object ref = cacheUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cacheUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string cacheUrl = 3;</code>
       * @return The bytes for cacheUrl.
       */
      public com.google.protobuf.ByteString
          getCacheUrlBytes() {
        Object ref = cacheUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cacheUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cacheUrl = 3;</code>
       * @param value The cacheUrl to set.
       * @return This builder for chaining.
       */
      public Builder setCacheUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        cacheUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cacheUrl = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCacheUrl() {

        cacheUrl_ = getDefaultInstance().getCacheUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string cacheUrl = 3;</code>
       * @param value The bytes for cacheUrl to set.
       * @return This builder for chaining.
       */
      public Builder setCacheUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        cacheUrl_ = value;
        onChanged();
        return this;
      }

      private Object smUrl_ = "";
      /**
       * <code>string smUrl = 4;</code>
       * @return The smUrl.
       */
      public String getSmUrl() {
        Object ref = smUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          smUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string smUrl = 4;</code>
       * @return The bytes for smUrl.
       */
      public com.google.protobuf.ByteString
          getSmUrlBytes() {
        Object ref = smUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          smUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string smUrl = 4;</code>
       * @param value The smUrl to set.
       * @return This builder for chaining.
       */
      public Builder setSmUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        smUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string smUrl = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSmUrl() {

        smUrl_ = getDefaultInstance().getSmUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string smUrl = 4;</code>
       * @param value The bytes for smUrl to set.
       * @return This builder for chaining.
       */
      public Builder setSmUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        smUrl_ = value;
        onChanged();
        return this;
      }

      private boolean isR18_ ;
      /**
       * <code>bool isR18 = 5;</code>
       * @return The isR18.
       */
      public boolean getIsR18() {
        return isR18_;
      }
      /**
       * <code>bool isR18 = 5;</code>
       * @param value The isR18 to set.
       * @return This builder for chaining.
       */
      public Builder setIsR18(boolean value) {

        isR18_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isR18 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsR18() {

        isR18_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.v1.PictureUrlData)
    }

    // @@protoc_insertion_point(class_scope:proto.v1.PictureUrlData)
    private static final PictureUrlData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PictureUrlData();
    }

    public static PictureUrlData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PictureUrlData>
        PARSER = new com.google.protobuf.AbstractParser<PictureUrlData>() {
      @Override
      public PictureUrlData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PictureUrlData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PictureUrlData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PictureUrlData> getParserForType() {
      return PARSER;
    }

    @Override
    public PictureUrlData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PictureUrlResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.v1.PictureUrlResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    String getMsg();
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>.proto.v1.PictureUrlData data = 3;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>.proto.v1.PictureUrlData data = 3;</code>
     * @return The data.
     */
    PictureUrlData getData();
    /**
     * <code>.proto.v1.PictureUrlData data = 3;</code>
     */
    PictureUrlDataOrBuilder getDataOrBuilder();
  }
  /**
   * Protobuf type {@code proto.v1.PictureUrlResponse}
   */
  public  static final class PictureUrlResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.v1.PictureUrlResponse)
      PictureUrlResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PictureUrlResponse.newBuilder() to construct.
    private PictureUrlResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PictureUrlResponse() {
      msg_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PictureUrlResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PictureUrlResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 26: {
              PictureUrlData.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(PictureUrlData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PictureSpiderService.internal_static_proto_v1_PictureUrlResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PictureSpiderService.internal_static_proto_v1_PictureUrlResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PictureUrlResponse.class, Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile Object msg_;
    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private PictureUrlData data_;
    /**
     * <code>.proto.v1.PictureUrlData data = 3;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <code>.proto.v1.PictureUrlData data = 3;</code>
     * @return The data.
     */
    public PictureUrlData getData() {
      return data_ == null ? PictureUrlData.getDefaultInstance() : data_;
    }
    /**
     * <code>.proto.v1.PictureUrlData data = 3;</code>
     */
    public PictureUrlDataOrBuilder getDataOrBuilder() {
      return getData();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (data_ != null) {
        output.writeMessage(3, getData());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PictureUrlResponse)) {
        return super.equals(obj);
      }
      PictureUrlResponse other = (PictureUrlResponse) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PictureUrlResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PictureUrlResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PictureUrlResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PictureUrlResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PictureUrlResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PictureUrlResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PictureUrlResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PictureUrlResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PictureUrlResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PictureUrlResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PictureUrlResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PictureUrlResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PictureUrlResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.v1.PictureUrlResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.v1.PictureUrlResponse)
        PictureUrlResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PictureSpiderService.internal_static_proto_v1_PictureUrlResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PictureSpiderService.internal_static_proto_v1_PictureUrlResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PictureUrlResponse.class, Builder.class);
      }

      // Construct using com.piggy.quincy.utils.picture.PictureSpiderService.PictureUrlResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        msg_ = "";

        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PictureSpiderService.internal_static_proto_v1_PictureUrlResponse_descriptor;
      }

      @Override
      public PictureUrlResponse getDefaultInstanceForType() {
        return PictureUrlResponse.getDefaultInstance();
      }

      @Override
      public PictureUrlResponse build() {
        PictureUrlResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PictureUrlResponse buildPartial() {
        PictureUrlResponse result = new PictureUrlResponse(this);
        result.code_ = code_;
        result.msg_ = msg_;
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PictureUrlResponse) {
          return mergeFrom((PictureUrlResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PictureUrlResponse other) {
        if (other == PictureUrlResponse.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PictureUrlResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PictureUrlResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {

        code_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       * @return The msg.
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {

        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        msg_ = value;
        onChanged();
        return this;
      }

      private PictureUrlData data_;
      private com.google.protobuf.SingleFieldBuilderV3<
          PictureUrlData, PictureUrlData.Builder, PictureUrlDataOrBuilder> dataBuilder_;
      /**
       * <code>.proto.v1.PictureUrlData data = 3;</code>
       * @return Whether the data field is set.
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
      /**
       * <code>.proto.v1.PictureUrlData data = 3;</code>
       * @return The data.
       */
      public PictureUrlData getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? PictureUrlData.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.v1.PictureUrlData data = 3;</code>
       */
      public Builder setData(PictureUrlData value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.v1.PictureUrlData data = 3;</code>
       */
      public Builder setData(
          PictureUrlData.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.v1.PictureUrlData data = 3;</code>
       */
      public Builder mergeData(PictureUrlData value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
              PictureUrlData.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.v1.PictureUrlData data = 3;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.v1.PictureUrlData data = 3;</code>
       */
      public PictureUrlData.Builder getDataBuilder() {

        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.v1.PictureUrlData data = 3;</code>
       */
      public PictureUrlDataOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              PictureUrlData.getDefaultInstance() : data_;
        }
      }
      /**
       * <code>.proto.v1.PictureUrlData data = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PictureUrlData, PictureUrlData.Builder, PictureUrlDataOrBuilder>
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PictureUrlData, PictureUrlData.Builder, PictureUrlDataOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.v1.PictureUrlResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.v1.PictureUrlResponse)
    private static final PictureUrlResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PictureUrlResponse();
    }

    public static PictureUrlResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PictureUrlResponse>
        PARSER = new com.google.protobuf.AbstractParser<PictureUrlResponse>() {
      @Override
      public PictureUrlResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PictureUrlResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PictureUrlResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PictureUrlResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public PictureUrlResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_v1_PictureUrlRequest_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_v1_PictureUrlRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_v1_PictureUrlData_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_v1_PictureUrlData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_v1_PictureUrlResponse_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_v1_PictureUrlResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023PictureSpider.proto\022\010proto.v1\032\034google/" +
      "api/annotations.proto\"]\n\021PictureUrlReque" +
      "st\022\014\n\004type\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022\r\n\005manga\030\003 " +
      "\001(\003\022\r\n\005cache\030\004 \001(\010\022\020\n\010uploadSM\030\005 \001(\010\"f\n\016" +
      "PictureUrlData\022\023\n\013originalUrl\030\001 \001(\t\022\017\n\007r" +
      "eferer\030\002 \001(\t\022\020\n\010cacheUrl\030\003 \001(\t\022\r\n\005smUrl\030" +
      "\004 \001(\t\022\r\n\005isR18\030\005 \001(\010\"W\n\022PictureUrlRespon" +
      "se\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022&\n\004data\030\003 " +
      "\001(\0132\030.proto.v1.PictureUrlData2r\n\rPicture" +
      "Spider\022a\n\nPictureUrl\022\033.proto.v1.PictureU" +
      "rlRequest\032\034.proto.v1.PictureUrlResponse\"" +
      "\030\202\323\344\223\002\022\022\020/api/picture-urlB:\n\036com.piggy.q" +
      "uincy.utils.pictureB\024PictureSpiderServic" +
      "eZ\002v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_proto_v1_PictureUrlRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_v1_PictureUrlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_v1_PictureUrlRequest_descriptor,
        new String[] { "Type", "Id", "Manga", "Cache", "UploadSM", });
    internal_static_proto_v1_PictureUrlData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_v1_PictureUrlData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_v1_PictureUrlData_descriptor,
        new String[] { "OriginalUrl", "Referer", "CacheUrl", "SmUrl", "IsR18", });
    internal_static_proto_v1_PictureUrlResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_v1_PictureUrlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_v1_PictureUrlResponse_descriptor,
        new String[] { "Code", "Msg", "Data", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
