server:
  port: 8090

spring:
  application:
    name: quincy

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtualHost: /

  data:
    mongodb:
      host: impiggy.cn
      port: 27017
      database: qqbot_kun
      authentication-database: qqbot_kun
      username: bot
      password: kun123

  redis:
    host: redis
    port: 6379
    database: 0
    password:
    timeout: 300ms

# 日志配置
logging:
  file:
    path: /var/logs