spring:
  profiles:
    active: prod

mirai:
  http:
    authKey: Usjwus927sS@$jswZ
    qq: 747460961
    api: http://tx.impiggy.cn:12345

redis:
  database: 'quincy'
  expire:
    common: 2592000 # 默认30d超时