server:
  port: 8090

spring:
  application:
    name: quincy

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtualHost: /

  data:
    mongodb:
      host: impiggy.cn
      port: 27017
      database: qqbot_kun
      authentication-database: qqbot_kun
      username: bot
      password: kun123

# 日志配置
logging:
  level:
    org.springframework.data.mongodb.core: debug
    com.macro.mall.mapper: debug
    com.macro.mall.portal.dao: debug